(load "boolean.scm")

(define (eqv? obj1 obj2)
  (cond ((and (boolean? obj1) (boolean? obj2))
         (boolean=? obj1 obj2))
        ((and (symbol? obj1) (symbol? obj2))
         (symbol=? obj1 obj2))
        ((and (number? obj1) (number? obj2))
         (= obj1 obj2))
        ((and (char? obj1) (char? obj2))
         (char=? obj1 obj2))
        (else #f)))
